name "example"
maintainer "The Authors"
maintainer_email "you@example.com"
license "all_rights"
description "Installs/Configures example"
long_description "Installs/Configures example"
version "0.1.0"
